package be.thomasmore.bookserver.model;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

import jakarta.persistence.*;
import java.util.Set;

/**
 * Represents an Author entity in the database.
 * This class is mapped to a database table using JPA annotations.
 * It has a many-to-many relationship with the Book entity.
 */
@NoArgsConstructor
@Data
@EqualsAndHashCode(exclude = {"books"})
@ToString(exclude = {"books"})
@Entity
public class Author {
    /**
     * Unique identifier for the author.
     * Automatically generated by the database.
     */
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    private int id;

    /**
     * Name of the author.
     * Cannot be null or blank.
     */
    @NotBlank(message = "Author name should not be blank")
    @NotNull
    private String name;

    /**
     * Many-to-many relationship with Book entity.
     * This is the inverse side of the relationship.
     * Uses lazy loading for better performance.
     * The relationship is managed by the 'authors' field in the Book class.
     */
    @ManyToMany(mappedBy = "authors", fetch = FetchType.LAZY)
    private Set<Book> books;

    /**
     * Constructor that creates an Author with the specified ID.
     * @param id The ID to set for the author.
     */
    public Author(int id) {
        this.id = id;
    }
}
