package be.thomasmore.bookserver.model;

import lombok.*;

import jakarta.persistence.*;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.util.List;

/**
 * Represents a Book entity in the database.
 * This class is mapped to a database table using JPA annotations.
 * It includes validation constraints and relationships with the Author entity.
 */
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Data
@EqualsAndHashCode(exclude = {"authors"})
@ToString(exclude = {"authors"})
@Entity
public class Book {
    /**
     * Unique identifier for the book.
     * Automatically generated by the database.
     */
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    private int id;

    /**
     * Title of the book.
     * Cannot be null or blank.
     */
    @NotBlank(message = "Book Title should not be blank")
    @NotNull
    private String title;

    /**
     * Price of the book in Euros.
     * Must be between 0 and 200.
     */
    @Min(value = 0, message = "price should not be smaller than 0")
    @Max(value = 200, message = "price should not be greater than 200")
    Integer priceInEur;

    //todo: clean up (with flyway)
    private String author = ""; //this is not normalized but I don't care for this example

    /**
     * Many-to-many relationship with Author entity.
     * Uses lazy loading for better performance.
     * The relationship is managed by the 'authors' field in the Author class.
     */
    @ManyToMany(fetch = FetchType.LAZY)
    private List<Author> authors;
}
